-- MySQL Script generated by MySQL Workbench
-- Wed Oct 21 21:42:19 2020
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `mydb` DEFAULT CHARACTER SET utf8 ;
USE `mydb` ;

-- -----------------------------------------------------
-- Table `mydb`.`store`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`store` ;

CREATE TABLE IF NOT EXISTS `mydb`.`store` (
  `storeID` INT NOT NULL,
  `spassword` VARCHAR(45) NULL DEFAULT NULL,
  `sname` VARCHAR(45) NULL DEFAULT NULL,
  PRIMARY KEY (`storeID`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `mydb`.`commodity`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`commodity` ;

CREATE TABLE IF NOT EXISTS `mydb`.`commodity` (
  `commodityID` INT NOT NULL,
  `store_storeID` INT NOT NULL,
  `cname` VARCHAR(45) NULL DEFAULT NULL,
  `price` VARCHAR(45) NULL DEFAULT NULL,
  `introduction` VARCHAR(1000) NULL DEFAULT NULL,
  `type` VARCHAR(45) NULL,
  `addedDate` DATE NULL DEFAULT NULL,
  `picName` VARCHAR(100) NULL,
  PRIMARY KEY (`commodityID`, `store_storeID`),
  INDEX `fk_commodity_store1_idx` (`store_storeID` ASC) VISIBLE,
  CONSTRAINT `fk_commodity_store1`
    FOREIGN KEY (`store_storeID`)
    REFERENCES `mydb`.`store` (`storeID`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `mydb`.`userinfo`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`userinfo` ;

CREATE TABLE IF NOT EXISTS `mydb`.`userinfo` (
  `username` VARCHAR(45) NOT NULL,
  `password` VARCHAR(45) NULL DEFAULT NULL,
  `birthday` DATE NULL DEFAULT NULL,
  `firstName` VARCHAR(45) NULL DEFAULT NULL,
  `lastName` VARCHAR(45) NULL DEFAULT NULL,
  PRIMARY KEY (`username`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `mydb`.`cart`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`cart` ;

CREATE TABLE IF NOT EXISTS `mydb`.`cart` (
  `username` VARCHAR(45) NOT NULL,
  `commodityID` INT NOT NULL,
  `number` INT NULL,
  PRIMARY KEY (`username`, `commodityID`),
  INDEX `fk_cart_userinfo1_idx` (`username` ASC) VISIBLE,
  INDEX `fk_cart_commodity1_idx` (`commodityID` ASC) VISIBLE,
  CONSTRAINT `fk_cart_userinfo1`
    FOREIGN KEY (`username`)
    REFERENCES `mydb`.`userinfo` (`username`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_cart_commodity1`
    FOREIGN KEY (`commodityID`)
    REFERENCES `mydb`.`commodity` (`commodityID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`order`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`order` ;

CREATE TABLE IF NOT EXISTS `mydb`.`order` (
  `orderID` VARCHAR(45) NOT NULL,
  `commodityID` INT NOT NULL,
  `username` VARCHAR(45) NOT NULL,
  `number` INT NULL,
  `date` DATETIME NULL,
  PRIMARY KEY (`orderID`, `commodityID`, `username`),
  INDEX `fk_buy_commodity1_idx` (`commodityID` ASC) VISIBLE,
  INDEX `username_idx` (`username` ASC) VISIBLE,
  CONSTRAINT `fk_buy_commodity1`
    FOREIGN KEY (`commodityID`)
    REFERENCES `mydb`.`commodity` (`commodityID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `username`
    FOREIGN KEY (`username`)
    REFERENCES `mydb`.`userinfo` (`username`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
